---
- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install php5
  sudo: yes
  apt: pkg=php5 state=latest

- name: Install PHP Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: php_packages

- name: Install php5-cli
  sudo: yes
  apt: pkg=php5-cli state=latest

- name: ensure timezone is set in cli php.ini
  sudo: yes
  lineinfile: dest=/etc/php5/cli/php.ini regexp='date.timezone =' line='date.timezone = {{ timezone }}'

- name: ensure timezone is set in apache2 php.ini
  lineinfile: dest=/etc/php5/apache2/php.ini regexp='date.timezone =' line='date.timezone = {{ timezone }}' 

- name: Install php5-dev
  apt: pkg="php5-dev" state=present

- name: Install Package PECL Packages
  shell: echo "\n\n\n\n\n\n\n\n\n" | pecl install {{ item }}
  register: pecl_result
  changed_when: "'already installed' not in pecl_result.stdout"
  failed_when: "pecl_result.stderr or ('ERROR' in pecl_result.stdout)"
  with_items: pecl_packages

- name: Create extension .ini file
  template: >
    src="extension.tpl"
    dest="/etc/php5/mods-available/{{ item }}.ini"
    owner="root"
    group="root"
    mode=0644
  with_items: pecl_packages

- name: Enable extesion
  shell: php5enmod {{ item }}
  with_items: pecl_packages

